import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"

[font]
size = 24.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
