session: dot

root: ~/Code/dotfiles

windows:
  - name: editor
    layout: main-horizontal
    commands:
      - vim
    panes:
      - commands:
        - git status
  - name: root
    root: ~/
    commands:
      - tree -L 1
