session: logseq

root: "/Users/andyhuynh/Library/Mobile\ Documents/iCloud~com~logseq~logseq/Documents/KMS"

windows:
  - name: editor
    layout: main-horizontal
    commands:
      - vim
    panes:
      - commands:
        - git status
  - name: root
    root: ~/
    commands:
      - tree -L 1

