#!/usr/bin/env ruby
require 'fileutils'

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving #{link_name} symlink"
    FileUtils.rm link_name
  elsif File.exists? link_name
    puts "\tSkipping because #{link_name} exists and is not a symlink."
    FileUtils.rm link_name
    return
  end

  FileUtils.ln_sf(path, link_name)
  puts "\tCreate symlink #{link_name} that points to #{path}\n\n"
end

puts "Bootstrapping Andy's Dotfiles..."

link("~/Code/dotfiles/ack/_ackrc", "~/.ackrc/")
link("~/Code/dotfiles/applescripts/current_track.sh", "~/.current_track.sh")
link("~/Code/dotfiles/git/_gitconfig", "~/.gitconfig")
link("~/Code/dotfiles/git/_gitignore_global", "~/.gitignore_global")
link("~/Code/dotfiles/misc/_spotify", "/usr/local/bin/spotify")
link("~/Code/dotfiles/pry/_pryrc", "~/.pryrc")
link("~/Code/dotfiles/tmux/_tmux.conf", "~/.tmux.conf")
link("~/Code/dotfiles/tmuxinator/", "~/.tmuxinator/")
link("~/Code/dotfiles/vim/_vimrc", "~/.vimrc")
link("~/Code/dotfiles/vim/vim", "~/.vim")
link("~/Code/dotfiles/zsh/_zshrc", "~/.zshrc")

puts "done"
