#!/usr/bin/env ruby
require 'fileutils'

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving #{link_name} symlink"
    FileUtils.rm link_name
  elsif File.exist? link_name
    puts "\tSkipping because #{link_name} exists and is not a symlink."
    FileUtils.rm link_name
    return
  end

  FileUtils.ln_sf(path, link_name)
  puts "\tCreate symlink #{link_name} that points to #{path}\n\n"
end

puts 'Bootstrapping Dotfiles...'

link('~/Code/dotfiles/config/asdf/_tool-versions', '~/.tool-versions')
link('~/Code/dotfiles/config/kitty/', '~/.config/kitty')
link('~/Code/dotfiles/config/spicetify/_spicetify', '~/.config/spicetify/.spicetify')
link('~/Code/dotfiles/config/nvim/', '~/.config/nvim')
link('~/Code/dotfiles/config/zsh/_zprofile', '~/.zprofile')
link('~/Code/dotfiles/config/zsh/_zshrc', '~/.zshrc')
link('~/Code/dotfiles/config/git/_gitconfig', '~/.gitconfig')
link('~/Code/dotfiles/config/git/_gitignore', '~/.gitignore')
link('~/Code/dotfiles/config/starship/starship.toml', '~/.config/starship.toml')

puts 'done'
