tap "homebrew/bundle"
tap "homebrew/services"

# Neovim workflow 
# tap "homebrew/cask-fonts"
# brew "neovim"
# brew "gh"
# brew "ripgrep"
# cask "font-caskaydia-cove-nerd-font"
# cask "font-fira-code-nerd-font"
# cask "font-hack-nerd-font"
# cask "font-inter"
# cask "font-symbols-only-nerd-font"

# Work setup
# brew "gmp"
# brew "coreutils"
# brew "libyaml"
# brew "readline"
# brew "openssl@1.1"
# brew "curl"
# brew "gnupg"
# brew "shared-mime-info"

# TODO: Figure out how to use asdf to install elixir
# brew "elixir"

brew "asdf"
brew "diff-so-fancy"
brew "git"
brew "mysql", restart_service: true
brew "postgresql"
brew "ruby-build"
brew "starship"

cask "1password"
cask "alfred"
cask "amethyst"
cask "authy"
cask "dash"
cask "discord"
cask "docker"
cask "dozer"
cask "google-chrome"
cask "jumpcut"
cask "kitty"
cask "logseq"
cask "signal"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"

vscode "alexkrechik.cucumberautocomplete"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "formulahendry.auto-rename-tag"
vscode "GitHub.remotehub"
vscode "mjmcloug.vscode-elixir"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-repositories"
vscode "ms-vsliveshare.vsliveshare"
vscode "Shopify.ruby-lsp"
vscode "vscodevim.vim"
vscode "zxh404.vscode-proto3"