#!/bin/bash
# This script creates symlinks from the home directory to the dotfiles in ~/.dotfiles

DOTFILES_DIR="/Users/andyhuynh/.dotfiles"
HOME_DIR="/Users/andyhuynh"

mkdir -p "$HOME_DIR/.config/aerospace"
mkdir -p "$HOME_DIR/.config/bat/themes"
mkdir -p "$HOME_DIR/.config/btop/themes"
mkdir -p "$HOME_DIR/.config/cbsh"
mkdir -p "$HOME_DIR/.config/mise"
mkdir -p "$HOME_DIR/.config/nvim/lua/config"
mkdir -p "$HOME_DIR/.config/nvim/lua/platform"
mkdir -p "$HOME_DIR/.config/nvim/lua/plugins"
mkdir -p "$HOME_DIR/.config/nvim/plugin/after"
mkdir -p "$HOME_DIR/.config/tmuxinator"
mkdir -p "$HOME_DIR/.config/zsh"

ln -sv "$DOTFILES_DIR/config/aerospace/aerospace.toml" "$HOME_DIR/.config/aerospace/aerospace.toml"
ln -sv "$DOTFILES_DIR/config/bat/themes/Catppuccin%20Frappe.tmTheme" "$HOME_DIR/.config/bat/themes/Catppuccin%20Frappe.tmTheme"
ln -sv "$DOTFILES_DIR/config/bat/themes/Catppuccin%20Latte.tmTheme" "$HOME_DIR/.config/bat/themes/Catppuccin%20Latte.tmTheme"
ln -sv "$DOTFILES_DIR/config/bat/themes/Catppuccin%20Macchiato.tmTheme" "$HOME_DIR/.config/bat/themes/Catppuccin%20Macchiato.tmTheme"
ln -sv "$DOTFILES_DIR/config/bat/themes/Catppuccin%20Mocha.tmTheme" "$HOME_DIR/.config/bat/themes/Catppuccin%20Mocha.tmTheme"
ln -sv "$DOTFILES_DIR/config/btop/btop.conf" "$HOME_DIR/.config/btop/btop.conf"
ln -sv "$DOTFILES_DIR/config/btop/themes/catppuccin_frappe.theme" "$HOME_DIR/.config/btop/themes/catppuccin_frappe.theme"
ln -sv "$DOTFILES_DIR/config/btop/themes/catppuccin_latte.theme" "$HOME_DIR/.config/btop/themes/catppuccin_latte.theme"
ln -sv "$DOTFILES_DIR/config/btop/themes/catppuccin_macchiato.theme" "$HOME_DIR/.config/btop/themes/catppuccin_macchiato.theme"
ln -sv "$DOTFILES_DIR/config/btop/themes/catppuccin_mocha.theme" "$HOME_DIR/.config/btop/themes/catppuccin_mocha.theme"
ln -sv "$DOTFILES_DIR/config/cbsh/config" "$HOME_DIR/.config/cbsh/config"
ln -sv "$DOTFILES_DIR/_gitconfig" "$HOME_DIR/.gitconfig"
ln -sv "$DOTFILES_DIR/_gitignore_global" "$HOME_DIR/.gitignore_global"
ln -sv "$DOTFILES_DIR/config/mise/config.toml" "$HOME_DIR/.config/mise/config.toml"
ln -sv "$DOTFILES_DIR/config/nvim/.gitignore" "$HOME_DIR/.config/nvim/.gitignore"
ln -sv "$DOTFILES_DIR/config/nvim/.neoconf.json" "$HOME_DIR/.config/nvim/.neoconf.json"
ln -sv "$DOTFILES_DIR/config/nvim/init.lua" "$HOME_DIR/.config/nvim/init.lua"
ln -sv "$DOTFILES_DIR/config/nvim/keymaps.txt" "$HOME_DIR/.config/nvim/keymaps.txt"
ln -sv "$DOTFILES_DIR/config/nvim/lazy-lock.json" "$HOME_DIR/.config/nvim/lazy-lock.json"
ln -sv "$DOTFILES_DIR/config/nvim/lazyvim.json" "$HOME_DIR/.config/nvim/lazyvim.json"
ln -sv "$DOTFILES_DIR/config/nvim/LICENSE" "$HOME_DIR/.config/nvim/LICENSE"
ln -sv "$DOTFILES_DIR/config/nvim/lua/config/autocmds.lua" "$HOME_DIR/.config/nvim/lua/config/autocmds.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/config/keymaps.lua" "$HOME_DIR/.config/nvim/lua/config/keymaps.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/config/lazy.lua" "$HOME_DIR/.config/nvim/lua/config/lazy.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/config/options.lua" "$HOME_DIR/.config/nvim/lua/config/options.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/platform/linux.lua" "$HOME_DIR/.config/nvim/lua/platform/linux.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/platform/macos.lua" "$HOME_DIR/.config/nvim/lua/platform/macos.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/colorscheme.lua" "$HOME_DIR/.config/nvim/lua/plugins/colorscheme.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/example.lua" "$HOME_DIR/.config/nvim/lua/plugins/example.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/obsidian.lua" "$HOME_DIR/.config/nvim/lua/plugins/obsidian.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/snacks-animated-scrolling-off.lua" "$HOME_DIR/.config/nvim/lua/plugins/snacks-animated-scrolling-off.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/telescope.lua" "$HOME_DIR/.config/nvim/lua/plugins/telescope.lua"
ln -sv "$DOTFILES_DIR/config/nvim/lua/plugins/vim-tmux-navigator.lua" "$HOME_DIR/.config/nvim/lua/plugins/vim-tmux-navigator.lua"
ln -sv "$DOTFILES_DIR/config/nvim/plugin/after/transparency.lua" "$HOME_DIR/.config/nvim/plugin/after/transparency.lua"
ln -sv "$DOTFILES_DIR/config/nvim/README.md" "$HOME_DIR/.config/nvim/README.md"
ln -sv "$DOTFILES_DIR/config/nvim/stylua.toml" "$HOME_DIR/.config/nvim/stylua.toml"
ln -sv "$DOTFILES_DIR/_tmux.conf" "$HOME_DIR/.tmux.conf"
ln -sv "$DOTFILES_DIR/config/tmuxinator/cb.yml" "$HOME_DIR/.config/tmuxinator/cb.yml"
ln -sv "$DOTFILES_DIR/config/tmuxinator/dfs.yml" "$HOME_DIR/.config/tmuxinator/dfs.yml"
ln -sv "$DOTFILES_DIR/config/tmuxinator/lab.yml" "$HOME_DIR/.config/tmuxinator/lab.yml"
ln -sv "$DOTFILES_DIR/keybindings.json" "$HOME_DIR/keybindings.json"
ln -sv "$DOTFILES_DIR/settings.json" "$HOME_DIR/settings.json"
ln -sv "$DOTFILES_DIR/tasks.json" "$HOME_DIR/tasks.json"
ln -sv "$DOTFILES_DIR/config/zsh/.zshrc" "$HOME_DIR/.config/zsh/.zshrc"
ln -sv "$DOTFILES_DIR/_zshenv" "$HOME_DIR/.zshenv"

if [[ "$(uname)" == "Linux" ]]; then
    mkdir -p "$HOME_DIR/.config/hypr"
    ln -sv "$DOTFILES_DIR/config/hypr/bindings.conf" "$HOME_DIR/.config/hypr/bindings.conf"
    ln -sv "$DOTFILES_DIR/config/hypr/input.conf" "$HOME_DIR/.config/hypr/input.conf"
    ln -sv "$DOTFILES_DIR/config/hypr/monitors.conf" "$HOME_DIR/.config/hypr/monitors.conf"
fi

echo "New symlinks created."