# ~/.config/tmuxinator/sb.yml

name: 🧪 lab
root: /tmp

windows:
  - 📖: nvim .
  - 📒:
      layout: main-vertical
      panes:
        - editor:
          - cd ~/Code/raycast-fabric/ && n .
        - shell:
          - cd ~/Code/raycast-fabric/ && npm run dev
  -  🛋️:
      layout: main-vertical
      panes:
        - editor:
          - cd ~/Code/couchbot && n .
        - dev:
          - cd ~/Code/couchbot && npm run dev
