name = "tman"
root = "~/Code/go/src/github.com/andy4thehuynh/tman/"
[[window]]
name = "editor"
[[window.panes]]
command = "vim"
[[window.panes]]
command = "git status"
[[window]]
name = "root"
root = "~/"
[[window.panes]]
command = "tree -L 1"
